services:
  - type: web
    name: legaxi-ivr
    runtime: docker
    plan: free
    envVars:
      - key: SINCH_APP_KEY
        value: 5981949f-a13f-45c5-aa5d-be5e7dbcc063
      - key: SINCH_APP_SECRET
        value: tJaOJlbUlU6DEZFpUQ3DgQ==
      - key: SINCH_FROM_NUMBER
        value: "+447418631394"
      - key: SERVER_URL
        sync: false
      - key: GAS_WEBHOOK_URL
        sync: false
      - key: PORT
        value: "3000"
