services:
  - type: web
    name: legaxi-ivr
    runtime: docker
    plan: free
    envVars:
      - key: ZADARMA_API_KEY
        value: "7160c986557a40199856"
      - key: ZADARMA_API_SECRET
        value: "873e28f828e60cdcb0cb"
      - key: ZADARMA_SIP
        value: "681294"
      - key: ZADARMA_CALLER_ID
        value: "+525598160911"
      - key: WHATSAPP_NUMBER
        value: "5544621100"
      - key: SERVER_URL
        value: "https://legaxi-ivr.onrender.com"
      - key: GAS_WEBHOOK_URL
        sync: false
      - key: PORT
        value: "3000"
